---
on:
  pull_request:

jobs:
  markdownlint:
    uses: Stromweld/github-workflows/.github/workflows/markdownlint.yml@main

  yamllint:
    uses: Stromweld/github-workflows/.github/workflows/yamllint.yml@main

  jsonlint:
    uses: Stromweld/github-workflows/.github/workflows/jsonlint.yml@main

  cookstylelint:
    uses: Stromweld/github-workflows/.github/workflows/cookstylelint.yml@main

#  integration:
#    runs-on: macos-latest
#    steps:
#      - name: Install software
#        run: brew install vagrant virtualbox chef-workstation
#      - name: Check out code
#        uses: actions/checkout@main
#      - name: Test-Kitchen
#        run: ./start_kitchen_test.sh

  check:
    if: always()
    needs:
      - markdownlint
      - yamllint
      - jsonlint
      - cookstylelint
#      - integration
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@main
        with:
          allowed-failures:
          allowed-skips:
          jobs: ${{ toJSON(needs) }}
